name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build Rust project
      run: cargo build --release

    - name: Set up GDScript environment
      run: |
        sudo apt-get update
        sudo apt-get install -y godot

    - name: Build GDScript project
      run: |
        godot --export "Linux/X11" ./build/ginpa.x86_64