name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run Rust linting
      run: cargo clippy -- -D warnings

    - name: Set up GDScript environment
      run: |
        sudo apt-get update
        sudo apt-get install -y godot

    - name: Run GDScript linting
      run: |
        godot --lint