name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run Rust tests
      run: cargo test --release

    - name: Set up GDScript environment
      run: |
        sudo apt-get update
        sudo apt-get install -y godot

    - name: Run GDScript tests
      run: |
        godot --run-tests